Feature/8689hx750/create-founder  - Feature/8689hx744/list-founder  - Feature/8689hx76a/edit-founder
BelenA25/pista8-admin pull request #10
Opened 2024-09-10 15:06 UTC by CristhianRF24

2024-09-10 21:12 UTC, BelenA25 commented on src/components/edit-button.tsx
> +  router.push(`/fundadores/edit/${itemId}`);
We could make this more reusable by doing something like this: router.push(`/${itemType}/edit/${itemId}`);

2024-09-11 18:31 UTC, MartinArispeRiveros approved these changes

2024-09-12 14:40 UTC, richi0085 requested changes

2024-09-12 14:40 UTC, richi0085 commented on src/app/fundadores/create/page.tsx
> +  'use client'
Why is the route called 'Founders,' and then we have 'Create'? Please ensure that even the route names are in English.

so :
founders/create

2024-09-12 14:40 UTC, richi0085 commented on src/app/fundadores/page.tsx
> +            <TableSection found={data} searchTerm={searchTerm} handleDelete={handleDelete} itemType={"founders"}></TableSection>
too large please do:
	<TableSection
			found="{data}"
			searchTerm="{searchTerm}"
			handleDelete="{handleDelete}"
			itemType={"founders"}
		></TableSection>
	</div>

2024-09-12 14:40 UTC, richi0085 commented on src/app/fundadores/page.tsx
> +            {!searchTerm && (<PaginationSection currentPage={currentPage} totalPages={Math.ceil(totalItems / itemsPerPage)} onPageChange={handlePageChange}></PaginationSection>)}
to large, please do:
	<PaginationSection
			currentPage="{currentPage}"
			totalPages={Math.ceil(totalItems / itemsPerPage)}
			onPageChange="{handlePageChange}"
		></PaginationSection>

2024-09-12 14:40 UTC, richi0085 commented on src/components/delete-button.tsx
> +import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "./ui/alert-dialog";
too large please do:
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from './ui/alert-dialog';

2024-09-12 14:40 UTC, richi0085 commented on src/components/side-menu.tsx
> +                  className={`w-full py-1 p-7 rounded-md transition-colors hover:bg-[#F2A594] ${getActiveClass(
refactor this to this:
className = {cn('w-full py-1 p-7 rounded-md transition-colors hover:bg-[#F2A594] ', getActiveClass(
                    MENU_ITEMS.STARTUPS.path
                  ))}

And fix this in all places where you have a dynamic class please

2024-09-12 14:40 UTC, richi0085 commented on src/components/founder-form.tsx
> +      getItemById(TYPE, founderId).then((founderData) => {
I prefer getFounderById is clear

2024-09-12 14:40 UTC, richi0085 commented on src/components/search-card.tsx
The component Name should be SearchCard.tsx

2024-09-12 14:40 UTC, richi0085 commented on src/components/founder-form.tsx
The component name should be FounderForm.tsx

2024-09-12 14:40 UTC, richi0085 commented on src/components/edit-button.tsx
The component name should be EditButton.tsx

2024-09-12 14:40 UTC, richi0085 commented on src/components/delete-button.tsx
the file name should be DeleteButton.tsx

2024-09-12 14:40 UTC, richi0085 commented on src/components/search-card.tsx
the file name should be SearchCard.tsx

2024-09-12 14:40 UTC, richi0085 commented on src/components/table-row-data.tsx
fill all please and read this!
https://rajithasanjayamal.medium.com/naming-conventions-best-practices-in-react-37624d020288

2024-09-12 15:10 UTC, CristhianRF24 commented on src/app/fundadores/create/page.tsx
> +  'use client'
I already corrected this in the last commitment I made

2024-09-12 21:56 UTC, richi0085 approved these changes

2024-09-12 22:07 UTC, merged