Feature/8689hx7m2/list-partners
BelenA25/pista8-admin pull request #12
Opened 2024-09-10 21:47 UTC by CristhianRF24

Complete the list partners user story

2024-09-11 18:26 UTC, MartinArispeRiveros requested changes

2024-09-11 18:26 UTC, MartinArispeRiveros commented on src/components/table-section.tsx
> +    part?:TableRowPartnersProps[];
@CristhianRF24 please fix format, space between ':' and property type

2024-09-11 18:26 UTC, MartinArispeRiveros commented on src/lib/utils.ts
>  export function cn(...inputs: ClassValue[]) {
@CristhianRF24 what means the nema method 'cn'. Is a reserved word in other case please rename

2024-09-12 21:16 UTC, MartinArispeRiveros approved these changes

2024-09-12 22:12 UTC, BelenA25 approved these changes

2024-09-12 22:13 UTC, merged