Feature/8689je9cp/list-startup-application
BelenA25/pista8-admin pull request #7
Opened 2024-09-05 16:12 UTC by CristhianRF24

I concluded the List Startup application  user story

2024-09-05 16:55 UTC, BelenA25 commented
You are making the pull request to main and not to the corresponding branch

2024-09-06 10:47 UTC, MartinArispeRiveros approved these changes

2024-09-06 12:56 UTC, BelenA25 approved these changes

2024-09-06 19:27 UTC, richi0085 requested changes

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/applications/addApplications/page.tsx
> +"use client";
Please move this logic to 
pages-components folder 
and here just import the component

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/applications/addApplications/page.tsx
> +      const newApplicationRef = ref(database, `applications/${Date.now()}`);
move this to applications service

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/applications/page.tsx
> +"use client";
move all logic to  page-components

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/applications/page.tsx
> +    const applicationsRef = ref(database, TYPE);
move this logic to a service please

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/applications/page.tsx
> +    if (currentPage === 1) {
1 is a magic number, please create a Cosnt

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/applications/page.tsx
> +    const searchQuery = query(
move all this to a service

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/page.tsx
>  import Title from "@/components/title";
move all logic to
page-components/startupsPage.tsx

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/page.tsx
> +    const [itemsPerPage, setItemsPerPage] = useState(6);
6 is a magic number

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/page.tsx
> +            const startupsReference = ref(database, 'startups');
move firebaselogic to a service

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/page.tsx
> +            if (currentPage === 1) {
1 is a magic number

2024-09-06 19:27 UTC, richi0085 commented on src/app/startups/page.tsx
> +            onValue(queryStartups, (snapshot) => {
move all firebase logic to a service

2024-09-06 19:27 UTC, richi0085 commented on src/components/application-form.tsx
> +const applicationSchema = z.object({
move this schema to shared/api/validation 
please

2024-09-06 19:27 UTC, richi0085 commented on src/components/application-form.tsx
> +    onSubmit(applicationData);
move all this to a clear method

2024-09-06 19:27 UTC, richi0085 commented on src/components/side-menu.tsx
> +                  alt=""
alt is important

2024-09-06 19:27 UTC, richi0085 commented on src/components/side-menu.tsx
> +                        {item === "Fundadores" && (
Fundadores is a magic strinc, create an enum if necesary

2024-09-09 12:48 UTC, richi0085 requested changes

2024-09-09 12:48 UTC, richi0085 commented on src/components/addApplications.tsx
> +      const applicationsRef = ref(database, "applications");
Could you create a service please 
an applicationsService.ts

and from locations you should just call the service
applicationsService.get (or, update, or delete) 

if you dont do it we will have a lot of repited code on the project

2024-09-09 12:48 UTC, richi0085 commented on src/components/pagination-section.tsx
> +    if (totalPages <= PAGE_RANGE * 2 + 1) {
what is *2 + 1 
Please lets not have magic numbers

2024-09-09 17:20 UTC, MartinArispeRiveros approved these changes

2024-09-09 18:58 UTC, richi0085 requested changes

2024-09-09 18:58 UTC, richi0085 commented on src/app/startups/applications/create/page.tsx
> +    <div className="container mx-auto p-4">
If a lot of views will have this class it shoul be a component called Layout or something like that

2024-09-09 18:58 UTC, richi0085 commented on src/components/search-card.tsx
> +            <Input type="text" value={searchTerm} onChange={handleSearchChange}  placeholder="Escribe el nombre del startup..." onKeyDown={handleKeyDown} className="flex-grow p-2 border border-gray-3
to large 
please do something like this:
		<Input
			type="text"
			value="{searchTerm}"
			onChange="{handleSearchChange}"
			placeholder="Escribe el nombre del startup..."
			onKeyDown="{handleKeyDown}"
			className="flex-grow p-2 border border-gray-300 rounded-l-lg focus:outline-none focus:ring-2 
                        focus:ring-green-500"
		/>

2024-09-09 18:58 UTC, richi0085 commented on src/components/side-menu.tsx
> +                        {item === "Fundadores" && (
solve it please

2024-09-09 19:16 UTC, MartinArispeRiveros approved these changes

2024-09-10 13:24 UTC, richi0085 approved these changes

2024-09-10 17:13 UTC, merged